### ISSUE TITLE
Twig errors on staging.mautic.org

### ISSUE THREAD

**Issue by heathdutton** [mautic/website#10]
An exception has been thrown during the rendering of a template ("The partial 'title' is not found.").
/var/www/html/themes/oc-theme-mautic-org/partials/forum_channel_main/topics.htm line 5

![screen shot 2018-09-07 at 5 26 48 pm](https://user-images.githubusercontent.com/302215/45243945-a025d180-b2c3-11e8-86d2-d613a433aa1a.png)

**Comment by RCheesley** [comment]
Unable to replicate - closing as this seems to have been resolved in earlier commits or with the forums being connected up.
