### ISSUE TITLE
"Latest" link is broken, is there a new one?

### ISSUE THREAD

**Issue by ikolubr** [mautic/website#100]
Hi guys,
I have a script to download Mautic automatically, it was using the link: https://www.mautic.org/download/latest until yesterday. I tried to use the script right now and the link is broken. Do you guys have a new link where it always points to the latest version of Mautic, or could you guys fix that one?

Thank you so much,

**Comment by ikolubr** [comment]
Thank you @RCheesley. The link would be mega beneficial as it was pointed to the latest.zip... so no need to change the script when a new version was released.

Hope you can do it.

Thank you,

**Comment by RCheesley** [comment]
@ikolubr now fixed, thanks for flagging it! :rocket:
