### ISSUE TITLE
Cant enter on Slack

### ISSUE THREAD

**Issue by dhilst** [mautic/website#101]
I'm trying to enter on Mautic Slack but I receive an error on site, https://www.mautic.org/slack

<img width="777" alt="image" src="https://user-images.githubusercontent.com/392820/86024097-f0bf6f00-ba02-11ea-9f31-728acfb34b14.png">

Any ideas?

**Comment by RCheesley** [comment]
Hi there,

Did you get the email?

**Comment by dhilst** [comment]
In fact I get it :), sorry
