### ISSUE TITLE
Bad URL redirection on mautic.org

### ISSUE THREAD

**Issue by nclv** [mautic/website#102]
The yellow button _"Start Contributing"_ on [the main page](https://www.mautic.org/) redirects to _https://contribute.mautic.org/about/how-can-i-contribute/developer_ (**404 Error**) when it should redirect to _https://contribute.mautic.org/contributing-to-mautic/developer_.

**Comment by RCheesley** [comment]
@NicovincX2 thanks for flagging this up, I have updated the link!
