### ISSUE TITLE
Searchbar on top right is inefficient

### ISSUE THREAD

**Issue by npracht** [mautic/website#11]
# Description
On top right of the v2 website, you have a search bar which is inefficient.
![capture d ecran 2019-02-13 a 09 30 21](https://user-images.githubusercontent.com/14075239/52697596-0947fa00-2f72-11e9-8e08-0e6c0d695139.png)

**Comment by RCheesley** [comment]
This is using the component https://octobercms.com/plugin/offline-sitesearch - but I can't find a search results page set up on the site, which might be why it doesn't do anything when you search for something.

Looking into this now.

**Comment by dbhurley** [comment]
The goal originally was to tie in Algolia for search.

**Comment by RCheesley** [comment]
> The goal originally was to tie in Algolia for search.

Ah that's useful to know! Will do a bit more reading up.

**Comment by RCheesley** [comment]
Seems like the Algolia component on the October CMS directory only indexes blog posts: https://octobercms.com/plugin/xeor-algolia (at least this is my understanding) whereas the site search one installed has a plugin-based extendability which enables indexing multiple components on the CMS (and writing your own if needed).

**Comment by RCheesley** [comment]
Looks like search is working - created a simple search page to test: http://staging.mautic.org/search - with the results page http://staging.mautic.org/search-results?q=mautic - looks like it's indexing blogs currently as pages will need to have some custom stuff done to be indexed. So it seems the search bar is the culprit.

**Comment by RCheesley** [comment]
Looks like there was some missing code on the partial for the site header, so it wasn't actually doing a search. Now is passing the query but not using the search results page so a step in the right direction!

**Comment by RCheesley** [comment]
Search is now executing on the search-results page I created - code for header block in use:

```
<div class="d-flex order-lg-4 ml-auto">
<form class="input-icon my-lg-0 d-none d-md-block" action="{{ 'search-results' | page }}" method="get">
<input name="q" type="text" class="form-control header-search" placeholder="Search&hellip;" autocomplete="on" tabindex="1">
<div class="input-icon-addon">
<i class="fe fe-search"></i>
</div>
</form>
```

**Comment by RCheesley** [comment]
Closing - the search results / search pages should be styled - see #50
