### ISSUE TITLE
Card header is not editable

### ISSUE THREAD

**Issue by npracht** [mautic/website#12]
# Description
Card header is not editable.
Useless like that. Should be editable to add an image or simply remove it ?

### Example
http://staging.mautic.org/mauticians/npracht
![capture d ecran 2019-02-13 a 09 33 01](https://user-images.githubusercontent.com/14075239/52698003-f08c1400-2f72-11e9-830c-c202857fac97.png)

**Comment by RCheesley** [comment]
Incorrect syntax being used to load the avatar:

```<div class="card-header" style="background-image: url({{ user.avatar.getPath() }});"></div>```

Changed to:
```<div class="card-header" style="background-image: url({{ user.avatarThumb(300) }})";"></div>```

**Comment by RCheesley** [comment]
@npracht this might need a bit more tinkering to actually get a decent size. I set it to pull the avatar image at 300px which seems to work, but on your image that results in goofy cropping. So may want to use cropping but couldn't get this to work: https://stackoverflow.com/a/49222806/8997363

**Comment by npracht** [comment]
What about making it squary like most of the time it is (Github, Gravatar, etc.) ?

**Comment by RCheesley** [comment]
Could do, but this requires a change to the CSS - unsure if this is being compiled from LESS/SASS so not touching CSS yet. I'll raise as a separate enhancement issue
