### ISSUE TITLE
cannot click on a listed result

### ISSUE THREAD

**Issue by npracht** [mautic/website#14]
# Description
On the page http://staging.mautic.org/mauticamps/mauticamp-paris/ if you try to click on a result listed in the bottom boxes:
![capture d ecran 2019-02-13 a 09 43 44](https://user-images.githubusercontent.com/14075239/52698502-e0c0ff80-2f73-11e9-9f63-7d061aa66314.png)

There is no link. Consequence, you cannot read the related content...

**Comment by RCheesley** [comment]
This is because the forums were not linked up. Connected them up now (see #13) so this should be resolved.
