### ISSUE TITLE
cannot join translation teams

### ISSUE THREAD

**Issue by npracht** [mautic/website#15]
# Description
You cannot join the translation team. When you click on `Join`, nothing happens.
Try here: http://staging.mautic.org/translations/french-fr

**Comment by RCheesley** [comment]
@kuzmany I think this might well be the same problem we had with the user group forums - it might be that the fix needs applying to the translation page/partial as well?

**Comment by kuzmany** [comment]
Join should work 
http://staging.mautic.org/translations/english-uk-gb
