### ISSUE TITLE
error on click in language forum

### ISSUE THREAD

**Issue by npracht** [mautic/website#16]
# Description
On http://staging.mautic.org/mauticamps/french-fr/forum try to click on "View all" or "Group Posts" and see it generates an error.
```
An exception has been thrown during the rendering of a template ("The partial 'title' is not found."). /var/www/html/themes/oc-theme-mautic-org/partials/forum_channel_main/topics.htm line 5
```

**Comment by RCheesley** [comment]
I think that this relates to #13 in that the groups need to be connected up to the correct forums

**Comment by RCheesley** [comment]
See also #57 which may be related

**Comment by RCheesley** [comment]
Closing this issue as unable to replicate and the URL structure itself is incorrect (which will be addressed in issues tagged).
