### ISSUE TITLE
wrong link to view mauticians members of a language group

### ISSUE THREAD

**Issue by npracht** [mautic/website#17]
# Description
On http://staging.mautic.org/translations/french-fr, Click on "Mautician" and it redirects to mauticamps. This is a wrong end page.

**Comment by RCheesley** [comment]
This is due to the incorrect sidebar menu being used - related issue #57 - sidebar is needed for translations  (or using a more dynamic architecture) so that the URL structures are correct.

**Comment by kuzmany** [comment]
Lets finish it here 

https://github.com/mautic/website/issues/57
