### ISSUE TITLE
related article link on blog is wrong

### ISSUE THREAD

**Issue by npracht** [mautic/website#22]
# Description
On a blog post, you have related articles. If you click on it, it drives you to the wrong page (posts list instead of post page).
Go http://staging.mautic.org/blog/post/identifying-your-target-market and click on one of those links:
![capture d ecran 2019-02-13 a 09 54 53](https://user-images.githubusercontent.com/14075239/52699170-6d1ff200-2f75-11e9-9ea9-937ee441cf13.png)

**Comment by RCheesley** [comment]
Fixed this - on the partial sidebars/blog.htm the post page link was incorrectly set to use the category. This was generating the category slug instead of the post slug.
