### ISSUE TITLE
missing feature request category on forum

### ISSUE THREAD

**Issue by npracht** [mautic/website#25]
# Description
On http://staging.mautic.org/forum, there is no `feature request` category.
Maybe it is called `ideas` ? If yes, i think it should be clearer and we could rename to `ideas & feature requests` ?

**Comment by dbhurley** [comment]
In the ideas category description we can add something that mentions feature requests.

**Comment by kuzmany** [comment]
Renamed and add description do each channel

http://staging.mautic.org/forum/channel/ideas
