### ISSUE TITLE
no content on developer side

### ISSUE THREAD

**Issue by npracht** [mautic/website#26]
# Description
On http://staging.mautic.org/developers subcategories, there is no content. I think this zone is very important and we should work on guidelines to help people while keeping them in certain standard.
That's (IMO) a **Mautic 3** project work also.

**Comment by RCheesley** [comment]
@npracht any chance you might be able to contribute some content for this section, or suggest some developers who could? I am happy to edit and proof read but don't have the technical skills to write the stuff directly.

If folk can provide enough of a bare-bones I could write something though.

Some ideas for content off the top of my head:

- The three existing topics on the staging site (creating a theme, plugin and email transport)
- How to set up Docker-based environments
- Managing test/live environments/deployments

I'm sure there's plenty others!

**Comment by kuzmany** [comment]
I think a lot of content exists on mautic.org and mautic.com 
Or somewehere else
Just need copy that
Maybe already migrated, there are lot of hidden migrated pages/posts in admin

**Comment by kuzmany** [comment]
I improve this section with right sidebar

**Comment by kuzmany** [comment]
Also we need clean up blog sections/categories
Now we have duplications 

http://staging.mautic.org/blog/category/developers

**Comment by RCheesley** [comment]
There is a developer blog, but that is more information about the project
which is of interest to developers.

The aim for this section seems to be more for tutorials and the like,
relevant to developers.

**Comment by RCheesley** [comment]
I've been working on this. It's not a duplication, there are a bunch of
blog entries which are focused at developers but which are not tutorials so
they would not fit under the developers & API section.

**Comment by kuzmany** [comment]
I vote for move all blogs/content related to devs to Devs sections.
We need divide both worlds marketing & devs definitely.

**Comment by RCheesley** [comment]
OK, so here are the developer marketing blogs: https://www.mautic.org/category/blog/developer/ - you think we should have all of those in the developer & api section on the new site (http://staging.mautic.org/developers)?  I disagree, I think they are blog articles and news, not reference material.

The developers & API section is aimed to be a 'help' section specifically for developers - a half-way house between the developer documentation (which is very code-heavy and not so much tutorial/how to do stuff) and the help articles (which are more focused toward integrators/administrators).

I know we had some discussions about this in an earlier issue thread with @npracht and @dbhurley about how it was to be different from the developer docs but maybe we need to define that more closely.

My understanding of how it would work is:

- Help section for integrators/administrators/beginners - tutorials for the common 'how do I do xyz with Mautic' questions - formal tone of voice, structured layout, clear references for more info, aim is to be a point of reference and answer the questions people ask on search engines (think inbound marketing)

- Developers & API section for developers & high-end administrators/integrators - advanced tutorials on how to do more complicated things with and for Mautic - formal tone of voice, structured layout, clear references for more info, aim is to be a point of reference and answer the questions people ask on search engines (think inbound marketing)

- Blog articles - marketing focused, telling the community something or promoting something (think push marketing). It might be about a new release and what to expect (so aimed more at developers), or celebrating a community member, or general marketing news, tips, ways to use Mautic, case studies, etc.  Tone of voice would be informal as they are written as blogs.  Aim is to widen the reach of Mautic, share news, stimulate conversation

So, I would suggest we retain a section in the blog for developer-oriented blog articles, and build up the developers help section with useful materials/tutorials over time.  We can invite community contributions for these and if I can get access to analytics I can review common questions people are asking.

**Comment by kuzmany** [comment]
Agree with that. Just put articles where it make sense for you. 
Maybe we should rename blog category Developers to something different, more logical.
Great work!

**Comment by RCheesley** [comment]
Yep, I think I called it developers marketing or something just so my tired brain didn't get confused! xD

**Comment by RCheesley** [comment]
I'm working on this from the content perspective. I've asked a couple of community members if they'll contribute or reach out to others who can do so.

**Comment by RCheesley** [comment]
No content as yet forthcoming so I am shifting this to a later release.
