### ISSUE TITLE
Add CTAs on FAQ

### ISSUE THREAD

**Issue by npracht** [mautic/website#28]
# Description
On http://staging.mautic.org/help, it would be awesome to have few CTAs like:
- [ ] request FAQ articles ---> like a pending list. We could consider cloning the voting feature ok that ? Then we know what to produce first depending on the community needs ?
- [ ] submit a content for a FAQ article ---> it would notify someone (a leader with a role) and this leader would have to approve.

**Comment by dbhurley** [comment]
Agreed, this should live in the right hand column.
