### ISSUE TITLE
terms and conditions missing

### ISSUE THREAD

**Issue by npracht** [mautic/website#29]
# Description
Terms and conditions of the website are missing.

**Comment by RCheesley** [comment]
Added a link to the Privacy Policy on the About page - http://staging.mautic.org/about - and set up the privacy policy page to reflect the layout of the about section, by adding the related pages and default layout.

**Comment by RCheesley** [comment]
@dbhurley @npracht do we need any further T&C's? I couldn't find anything on the current Mautic site that was clearly linked to from any nav structures, found the privacy policy via Google search.

For example, I added the contributors agreement which I guess should also be in this section?
