### ISSUE TITLE
Poor contrast between text on .com site

### ISSUE THREAD

**Issue by RCheesley** [mautic/website#3]
There is poor contrast between the text and the black background on mautic.com:

http://nimb.ws/Z7LQPU

Ideally the font should be a different colour, maybe white or a whiter grey, so that it can be seen easily!

**Comment by escopecz** [comment]
Thanks for the report. However, Allyde and its service problems should be reported to Allyde. Also, there is no way ho to know on what URL you took the screen shot. That makes it hard to find that problem.

**Comment by RCheesley** [comment]
OK, just trying to be helpful. It was on mautic.com.

Ruth
On 23 Sep 2015 03:07, "John Linhart" notifications@github.com wrote:

> Thanks for the report. However, Allyde and its service problems should be
> reported to Allyde. Also, there is no way ho to know on what URL you took
> the screen shot. That makes it hard to find that problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mautic/website/issues/3#issuecomment-142516675.

## 

Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by RCheesley** [comment]
This is an old issue relating to the .com site so closing it.
