### ISSUE TITLE
missing cookie manager to be GDPR compliant

### ISSUE THREAD

**Issue by npracht** [mautic/website#30]
# Description
To be in rights with GDPR (european law), we should add a missing cookie manager. This one is very easy to install and includes most of the cookies providers: https://github.com/AmauriC/tarteaucitron.js/

**Comment by RCheesley** [comment]
https://octobercms.com/plugin/code200-eucookielawmadness  this seems to be the most popular one with October CMS.

This one uses implied consent: https://octobercms.com/plugin/cggstudio-cookielawbanner 

Depends on what you want to go for - and cookies aren't actually that relevant to GDPR, really ;)

**Comment by RCheesley** [comment]
Implemented carlosrgzm-cookieconsent plugin and added component to all pages using the light-bottom theme. Linking to the privacy policy for more info.
