### ISSUE TITLE
strong marketplace manager

### ISSUE THREAD

**Issue by npracht** [mautic/website#33]
# Description
I think for the future of mautic (must be in the mautic 3 roadmap), we should start to consider a more controled market place as does other open source projects.

## Suggestions

- [ ] Ability to submit a plugin
- [ ] Any plugin should be approved (technically with some requirements) manually or automatically (or a mix)
- [ ] Ability to offer it for free or with a specific price
- [ ] Installable with one click from the interface of M3
- [ ] Having a "reseller" space
- [ ] The community should keep a % of the turnover (it would give us some budget to manage new things)
- [ ] Manage version of plugins with description (mautic version compatibility, etc.)

**Comment by RCheesley** [comment]
From what I can see the current plugin allows you to submit and review, manage versions (but I can't see how this works in the back-end gui), but that's about it.

**Comment by kuzmany** [comment]
Current marketplace it's just simple directory for plugins
Definitely need marketplace with one click installation and add free/buy options to increase devs motivation build better plugin. 
John mentioned it here https://johnlinhart.com/blog/my-mautic-3-wishlist

@escopecz do you have some experience with this? best practice?

**Comment by escopecz** [comment]
I've submitted several extensions to other PHP OSS projects. I wouldn't call any ideal but we can take some ideas from them.

### Joomla Extensions

https://extensions.joomla.org

A developer submits a zip file with the extensions. It goes through automatic scan. If there is something fishy it goes through manual validation process. It scans for methods like `base64` which can be used to hide some stuff. Or `eval`.

### WordPress plugins

https://wordpress.org/plugins

Devs won't upload a zip package with the code but they use internal SVN to upload a plugin and also release new versions of it. It's an improvement over a zip package, but it's a PITA to use over Git.

### Grav plugins

https://getgrav.org/downloads/plugins

It uses only public GitHub repositories. That's pretty simple solution although it won't work for paid plugins. Grav has also nice tool called [Grav Package Manager](https://learn.getgrav.org/15/cli-console/grav-cli-gpm) which works a little like Composer. A plugin can define dependencies on other plugins so when a plugin is installed it can install several others that it is built on.

### Notes

- None of the extension directories have a "buy" button I think. I wouldn't consider it for the first version either. 
- It would be great if the devs could submit a link to their git repo. If it's private then they would add access for the Mautic Marketplace by a public key. But let's focus on public repos from start.
- It should be built as a API server so it could have a public website as well as UI in the Mautic administration.
- Each plugin should define what Mautic, PHP and possibly even MySql/MariaDb versions it supports and users could install it only when all the requirements are met.
- Users would get notification if new version of the plugin is released as new tag on the git repo.
- There should be a rating and comments functionality so the community could place feedback to the plugins. I don't think we will be able to review all plugins by some core team authority. But an automatic scan would be great.
- Big question is the dependency management. It'd be great if we could use Composer for it.

**Comment by RCheesley** [comment]
Some great feedback, perhaps we need to review what is already in place on
the marketplace on staging (eg public repo links are already there) and
prioritise what features we feel need to be implemented?

We can't do all of these in the first release but I'm sure with some
development support we could implement some in subsequent releases.

**Comment by kuzmany** [comment]
- dependency is the most important thing, many of my plugins use composer like this https://github.com/mtcextendee/mautic-barcode-generator-bundle
- zip upload is the worst scenario, from my dev side I am able to serve stable solution just from one source (github)
- plugins for Mautic at the moment have two ways of install - manual or composer, this is why we can't use zip file in current marketplace, plugins like https://github.com/mtcextendee/mautic-barcode-generator-bundle can't install by zip

- but anyway these marketplace topic is for future, on new website we will use very simple github directory to developers work

**Comment by RCheesley** [comment]
I like how October represent dependencies on other plugins - it shows you
really clearly on the marketplace listing what plugins need to be installed
to work with the plugin you're viewing.

So in addition to the code dependencies that might also be useful to have
as an option.

It feels like the marketplace itself is a separate project in itself
really, perhaps?

**Comment by kuzmany** [comment]
> It feels like the marketplace itself is a separate project in itself
really, perhaps?

Definitely.
