### ISSUE TITLE
Image files missing on current mautic.org site logos page

### ISSUE THREAD

**Issue by RCheesley** [mautic/website#36]
Identified when working on #23 
The following files are missing:

-  Dark background horizontal SVG no tagline https://www.mautic.org/media/logos/notagline/horizontal/Mautic_Logo_RGB_DB.svg
- Light background PDF logo https://www.mautic.org/media/logos/logo/Mautic_Logo_LB.pdf
- Light background SVG logo https://www.mautic.org/media/logos/logo/Mautic_Logo_LB.svg
- Dark background PDF monochrome logo https://www.mautic.org/media/logos/logo/Mautic_Logo_Monochrome_DB.pdf
- Dark background SVG monochrome logo https://www.mautic.org/media/logos/logo/Mautic_Logo_Monochrome_DB.svg

**Comment by RCheesley** [comment]
@dbhurley can you please track down the missing files mentioned in this issue?

**Comment by kuzmany** [comment]
What is state of this?

**Comment by RCheesley** [comment]
Waiting for @dbhurley to respond/provide
