### ISSUE TITLE
reset password email incorrect

### ISSUE THREAD

**Issue by npracht** [mautic/website#39]
# Description
Try to reset your password, you'll see that the content of the email is not appropriated.
**Subject and sender to modify, body of the message eventually.**

**Comment by RCheesley** [comment]
- Changed from name to Mautic
- Email template seems to be fine
- Removed app name from default template footer

![screenshot-mail google com-2019 02 14-18-27-03](https://user-images.githubusercontent.com/2930593/52808608-34bc0900-3086-11e9-8786-ee6badea2f73.png)
