### ISSUE TITLE
useless question tag button ?

### ISSUE THREAD

**Issue by npracht** [mautic/website#43]
# Description
On http://staging.mautic.org/forum/topic/mautic-installation-different-websites, you have a small question tag button you can click. What is it for ?
![capture d ecran 2019-02-13 a 11 56 36](https://user-images.githubusercontent.com/14075239/52706753-71084000-2f86-11e9-8ae3-a96927fbdcc5.png)
![capture d ecran 2019-02-13 a 11 56 40](https://user-images.githubusercontent.com/14075239/52706791-82e9e300-2f86-11e9-8c32-8f9777d73ca1.png)

**Comment by dbhurley** [comment]
The question allows for people to specify if an answer has been provided and mark it as “solved”

**Comment by npracht** [comment]
Ok then we should add a tooltip or a little text next to it like `Did this answer helped ?`

**Comment by kuzmany** [comment]
Remove voting, this feature is not finished yet.
Added description to helpful icon

![image](https://user-images.githubusercontent.com/462477/55613579-58005c00-578b-11e9-913e-6c5f217a266d.png)
