### ISSUE TITLE
documentation management

### ISSUE THREAD

**Issue by npracht** [mautic/website#47]
# Description
There is a page where you can find a piece of documentation. Why would we bring documentation on the website knowing that the doc is already existing on mautic.org/docs
**Isn't risky to have twice a doc?**

http://staging.mautic.org/getting-started

**Comment by dbhurley** [comment]
These docs are end user not developer docs.

**Comment by npracht** [comment]
Yes both of them. My question is why would we bring content concerning the end user doc on the website itself knowing that the end user doc is already on https://mautic.org/docs ? that means we'll have to maintain the doc twice.
I'd rather see a link from the website to the gitbook ?

**Comment by dbhurley** [comment]
The Gitbook docs are hard to maintain, formatted terribly and do not cover the topics that are in the website. These are docs for the marketer not the developer and they will not go to Gitbook for the answers they are seeking (nor should they)

**Comment by npracht** [comment]
So if i understand well, we would move from the gitbook documentation (user) to the documentation on the website, correct ? :)

**Comment by dbhurley** [comment]
For now leave Gitbook alone. Those are docs related to specific components of the platform. The website discusses _how_ to do something. Subtle difference I know.

**Comment by RCheesley** [comment]
So I guess the difference is that the gitbook docs are like an engineers manual for those who like to DIY. The developers docs are the technical drawings of how the engine works for folk who build engines or stuff that works with the engines - or the DIY'ers who want to do more. 

The stuff that will sit on this site will be 'how to drive the car and do it well/properly'?

**Comment by dbhurley** [comment]
Thank you Ruth, I was clearly struggling to describe that. Yes. This.

**Comment by kuzmany** [comment]
But at the moment users cannot add/edit documentation on staging?
I am using GitBook on https://docs.mtcextendee.com/ and I didn't notice any issue. Something like Wordpress
