### ISSUE TITLE
Review Discourse as possible forum platform

### ISSUE THREAD

**Issue by RCheesley** [mautic/website#54]
The current forum has several problems and may not be fit for purpose. Discourse may be a valid alternative option but consideration needs to be given to ensure it would meet the current/future needs of the community and could be seamlessly integrated into the existing October CMS site.

To do:

- [ ] Install Discourse

- [ ] Set up basic features/structure per current implementation on October CMS forum

- [ ] SSO feasibility

- [ ] Integration within October CMS platform feasibility

- [ ] Import of existing forum threads and users feasibility

**Comment by kuzmany** [comment]
I am not fan of Discourse. That style make me headache :)

**Comment by RCheesley** [comment]
@kuzmany from a community management and technical aspect I have my concerns that the RainLab forum will hold up beyond anything more than our early beta testing - hence the issue for discussion.  

Given the scale that the Mautic community is currently (~5300 on slack as a starting point) and expectations to grow further as adoption increases, we have to think with the big-picture both from the architecture/scalability and the user experience.

There don't seem to be (at least I have not found any documentation suggesting that there are) any kind of thread management processes on RainLab, moderation/anti-spam/heuristics, automated onboarding processes, etc.  The search system seems to be falling over with only a few thousand threads (see #21 for preliminary tests - needs a bit more digging) which in itself is not something that would work unless it could be fixed - or we could find a different way to manage the search (see also #49 which may be worth exploring).

On the plus side, Discord is fully customisable on the front-end, and could be pulled in via their well-documented API: http://docs.discourse.org which based on my understanding, means that we could control the styling fully and integrate it with our site styling, and we could use single sign-on to connect the current site with the forum? It could also be used to manage comments on articles/blogs as well as the forum.

It also handles scale well and has a lot of features that help keep things organised - for example merging topics, automated help features, while-you-type searching of existing threads, etc.

So, I guess the question/discussion is do we try to make the RainLab forum work, or do we consider feasibility of implementing an alternate system (there may be others to consider than Discord, it's just the one I am familiar with and it was suggested in discussions with David)

**Comment by RCheesley** [comment]
Pleased to close this as completed :)
