### ISSUE TITLE
Analytics/tracking for site on launch

### ISSUE THREAD

**Issue by RCheesley** [mautic/website#62]
At present we have not tested any analytics/tracking on the staging.mautic.org site.

The live site has GA tracking so we should consider how to deploy this.

I'd recommend using GTM and embedding the GA tracking that way, for ease of management. We may also deploy New Relic tracking this way.

@dbhurley should I set up a GTM container, or do you have one already that you can add me to? Could I be added to GA?

**Comment by kuzmany** [comment]
Confirmed, no tracking code  on staging

GA ID from mautic.org -  UA-55195964-1

Tagmanager would be  helpful

**Comment by RCheesley** [comment]
@dbhurley please share Analytics with my a/c? 

Also assume it's OK for me to create a GTM container and share it with your a/c for the mautic.org site? Need to ensure continuity of ownership.

**Comment by RCheesley** [comment]
No longer relevant
