### ISSUE TITLE
Getting started page: download doesn't work

### ISSUE THREAD

**Issue by RCheesley** [mautic/website#67]
http://staging.mautic.org/help/getting-started# the section for download seems to be missing - also the accordion isn't working.

Either need to fix or remove!

**Comment by kuzmany** [comment]
Can you rework the content to blog structure just content? 

http://staging.mautic.org/help/getting-started#

**Comment by RCheesley** [comment]
Yes, I'll take a look tomorrow!

**Comment by kuzmany** [comment]
This is fixed
We can improve content in the future (screenshots etc)
http://staging.mautic.org/help/getting-started
