### ISSUE TITLE
Migrate forums prior to launch

### ISSUE THREAD

**Issue by RCheesley** [mautic/website#69]
Forums are still being actively used, therefore forums and users will need to be re-migrated prior to site launch.

See: https://www.mautic.org/activity/ for recent activity and https://www.mautic.org/mauticians/ for user profiles

**Comment by kuzmany** [comment]
I thought forum was closed times ago.
But I will look on existed migrations script.  Hope It shouldn't pain process

**Comment by RCheesley** [comment]
I don't think they were, at least when I checked the forums yesterday I
could see new post activity.

**Comment by RCheesley** [comment]
https://www.mautic.org/forums/forum/ideas/
https://www.mautic.org/forums/forum/3rd-party-addons/ 

These seem to be the two forums which have had new activity over the past month.

**Comment by kuzmany** [comment]
Do we need migration? IMHO I sacrifice that data prior to launch new website soon. 
We don't loose to much. What do you think? 
And I will safe several hours of my work ;)

**Comment by RCheesley** [comment]
I think we need to look at how much data might be missed (how many forum
threads for example).

Can you get a sense of that?

**Comment by RCheesley** [comment]
@kuzmany at a quick glance, our forums are showing threads from 11 months ago. We have posts up to last week. I think we need to bring across users & forum threads before we migrate otherwise we stand to lose a lot of content and user accounts.

**Comment by RCheesley** [comment]
@dbhurley @kuzmany I believe that you may have agreed to lose the user accounts and content from the past ten months, is this correct?

I don't have access to see how many users/how much content this might involve, but I see content in user group forums, and some in the ideas forum, which we will lose. Plus of course the users who have created accounts - I've come across a few missing users when working with the mauticamp groups today.

Could we maybe compromise by importing new users who have logged in during the last 10 months? Would that be feasible?

I can't see analytics so I can't tell whether the content for the user group forums is worth migrating (e.g. whether people are actually accessing it or not) so I'm in the dark as far as that side of things goes.

**Comment by RCheesley** [comment]
No longer relevant
