### ISSUE TITLE
Contact Information - Getting Involved link not correct

### ISSUE THREAD

**Issue by phil-davis** [mautic/website#7]
Not sure if this is a place to report this, since the code/text of the website is not here!

At https://www.mautic.org/about/contact-information/?option=com_content&view=article&id=23&catid=9&Itemid=120

The "Get Involved page" link is pointing back to the contact-information page.

It should point to something like:
https://www.mautic.org/get-involved/

**Comment by jseevers** [comment]
Thanks Phil! Seems that page was a little dated. We appreciate you bringing it to our attention. The link has been fixed.
