### ISSUE TITLE
User card on blog article is not populating

### ISSUE THREAD

**Issue by RCheesley** [mautic/website#71]
This is pulling from component_usergroup/user-card-small.htm

When a blog article has a user associated with it, their avatar and details should show on the right hand side, with a link to their profile.

![screenshot-staging mautic org-2019 03 12-12-12-56](https://user-images.githubusercontent.com/2930593/54199183-324fa200-44c0-11e9-8a58-2aa25956edd1.png)

Currently it is not being pulled through, and is using /default for their profile.

If we can fix this then great, if not let's remove the user card partial from the blog_posts_single/default.htm partial and fix it in v1.1

**Comment by kuzmany** [comment]
Fixed http://staging.mautic.org/blog/post/community-team-changes

**Comment by RCheesley** [comment]
Perfect, that's great!
