### ISSUE TITLE
Minor fix on pagination for blog posts category view

### ISSUE THREAD

**Issue by RCheesley** [mautic/website#72]
Currently seems to be unstyled, see below

![screenshot-staging mautic org-2019 03 12-13-08-52](https://user-images.githubusercontent.com/2930593/54202489-105a1d80-44c8-11e9-9b6b-c11f80d9ab02.png)

**Comment by kuzmany** [comment]
Fixed http://staging.mautic.org/blog?page=2

**Comment by RCheesley** [comment]
Looks great!
