### ISSUE TITLE
Content sticks to the footer rather than header

### ISSUE THREAD

**Issue by escopecz** [mautic/website#88]
It's probably on every page but best visible on the download page with higher resolution monitor:

http://staging.mautic.org/download

![Screenshot 2019-04-23 at 12 42 33](https://user-images.githubusercontent.com/1235442/56575210-75c02480-65c5-11e9-824c-f066ba2096ce.png)

There is big gap between the div with logo and div with top menu.

**Comment by escopecz** [comment]
It seems to be related to
```
*, *::before, *::after {
    box-sizing: border-box;
}
```
As if I turn it off the gap is gone. But then the columns in the content too.

**Comment by escopecz** [comment]
Better solution is probably to turn off these and the page looks good:
```
.page {
    /* display: -ms-flexbox; */
    /* display: flex; */
    /* -ms-flex-direction: column; */
    /* flex-direction: column; */
    /* -ms-flex-pack: center; */
    /* justify-content: center; */
    min-height: 100%;
}
```

**Comment by RCheesley** [comment]
Applied this fix to staging which seems to resolve the issue. Not sure what that code was for but it might need revisiting just in case it breaks the world - do we have access to cross-browser testing?

**Comment by escopecz** [comment]
Thanks Ruth! I'm not sure we have.
