### ISSUE TITLE
clarify which website this repository refers to

### ISSUE THREAD

**Issue by aspiers** [mautic/website#95]
IIUC, there are two websites:

- https://www.mautic.org/ - the FOSS community site
- https://www.mautic.com/ - the commercial site owned and run by Mautic, Inc. / Acquia

I assume that this repository is only concerned with mautic.org, but either way I think it's important to clarify.  I suggest updating the README and also renaming the repository to https://github.com/mautic/mautic.org, or https://github.com/mautic/mautic.com if my assumption is wrong.  The rename should not break anything since GitHub would automatically set up redirects.

**Comment by RCheesley** [comment]
Indeed, it relates to Mautic.org. The branches are currently being used and
when the site deploys I would expect we would merge to master and remove
anything not being used, at which point the readme file can be updated to
give direction on how to be involved with the website team.

**Comment by aspiers** [comment]
Thanks Ruth.  If the expectation is to merge into `master` (rather than force-push), is there any reason not to update the README right away?

**Comment by aspiers** [comment]
To clarify, I could submit a simple PR just changing the README to clarify that this repo relates to mautic.org.  The directions on how to be involved could come later.

**Comment by RCheesley** [comment]
The Mautic organisation this repo belongs to us the Mautic.org one, there
is a separate organisation for the commercial side.

Certainly something that can be taken into account to make it clear how
people can get involved though once things are clearer regarding the
website, thanks for flagging it.

**Comment by aspiers** [comment]
OK, I've submitted #96 to address this.  This will still allow merging from the other branches to master when they are ready.
